### ISSUE TITLE
update for arduino-audio-tools

### ISSUE THREAD

**Issue by annD-annD** [klein0r/esp32-smarthome-center#2]
Hi,

thanks a lot for the great esp32-smarthome-center as a demonstration with many possibilities for audio kits. I tried it with ioBroker, sayit-adapter and a mqtt doorbell output from wago pfc200 and it works out of the box.

Are there any thoughts in updating the arduino-audio-tools (https://github.com/pschatzmann/arduino-audio-tools), because I realize a short interruption on the end of each text-to-speech file from sayit. I think the following release note in v0.9.2 might improve this:

Error Correction for Audio Player which is stopping too early

Thanks a lot,
annD

**Comment by klein0r** [comment]
> Are there any thoughts in updating the arduino-audio-tools

Feel free to update that dependency before building the project.

**Comment by annD-annD** [comment]
I had a short try, but I did not dive into the different changes in the new library.
